### PR TITLE
Update domains.txt

### PR DESCRIPTION
**Pull request by sitle**
Just add another domain name.

### CODE REVIEW

**Comment by sitle** [comment]
Actually, the domain name I added before this, doesn't work. So i add my subdomain name.

**Comment by sitle** [comment]
@benbalter : can you merge my PR plz. Thanks.

**Comment by benbalter** [comment]
@sitle `informatique.gov.pf` is a subdomain of `gov.pf`, which [should be whitelisted](https://github.com/benbalter/gman/blob/master/config/domains.txt#L3033).

**Comment by sitle** [comment]
@benbalter ok thanks for your reply. I don't understand why it doesn't work when i subscribe in the group.

**Pull request closed without merging**
