### PR TITLE
Add @codefor and @amsterdam for netherlands

### PR DESCRIPTION
**Pull request by brntbeer**
heyyyyyyy @benbalter et al, I got a request from a local Dutchy to add these two domains. 

`@amsterdam` seems normal, but i wasn't sure if we add organizations like `codefor.nl`? From the http://www.codefor.nl/ website it says (translated from googles):

> The Dutch Code for NL Foundation is the Dutch network of open source developers and designers who work together on the digital government.
>
> Our goal is the successful digital transformation of municipalities, other governments and society as a whole.
>
>Code for NL is governing partner of the international Code for All network.

[Seems Legit](http://i.imgur.com/xisRvmp.gif) to me!

### CODE REVIEW

**Comment by brntbeer** [comment]
Looks like the build is failing based on ruby version set in `.ruby-version`. needs to be 2.3 instead of 2.3.1 maybe

> Error: Unsupported Ruby version 2.0 found in `TargetRubyVersion` parameter (in .rubocop.yml). 2.0-compatible analysis was dropped after version 0.50.
Supported versions: 2.1, 2.2, 2.3, 2.4

**Comment by benbalter** [comment]
@brntbeer thanks for this. Is `codefor.nl` a government agency or a non-profit that supports government? Put another way, if I email `foo@codefor.nl` am I guaranteed to get a government employee?

**Comment by bvhme** [comment]
CodeForNL is a non-profit, Amsterdam is the city. 

This is why I made a PR that is just Amsterdam.nl, however it has been flagged as a duplicate in relation with this one #154

**Comment by brntbeer** [comment]
@benbalter schwoops, turns out just `@amsterdam.nl` is needed. I've update this PR appropriately for that 🙇

**Comment by jbjonesjr** [comment]
this raises an interesting question: gman is for govt domains, but gman restricts access to the govt community, which also includes resources for civic technology groups.

Traditionally those civic tech groups have members who also have a (govt-sponsored) email that gets them access, but not always. 

For now, the precedence is to not include codefor.... groups in gman.

**Pull request merged**
