### PR TITLE
Update domains.txt

### PR DESCRIPTION
**Pull request by TommyPujol06**
Add Africa To The List

### CODE REVIEW

**Comment by TommyPujol06** [comment]
Hi @benbalter ,

Could you review the changes ?

Thank you.

**Comment by benbalter** [comment]
@TommyPujol06 Can you share a bit more about the domains you'd like added? Thanks.

**Comment by TommyPujol06** [comment]
For example ?

**Comment by TommyPujol06** [comment]
@Tomoli75 Why won't they be safe if they are from the Goverment of Africa, I know you can get them for free as I did for my website : https://tommypujol.cf/  but the gov.cf and pujol.cf are secure.

**Comment by TommyPujol06** [comment]
Why not ?

**Comment by Tomoli75** [comment]
I do not trust this AT ALL. These are free domains, and there is no server IP address. Governments put actual websites onto their domains, don’t they?

**Comment by TommyPujol06** [comment]
There are actual websites try to connect to them with an African approved VPN and try again. These are NON-accessible pages for the people outside Africa. We can't see them.

**Comment by TommyPujol06** [comment]
I also need to wait for the nasa.gov for that but you trust it ? Don't you ? 
I don't even get an ipv4 address
prove

**Comment by TommyPujol06** [comment]
@Tomoli75 I guess I'll close the request #167 if you won't help.
Thanks

**Pull request closed without merging**
